// Generated by Wrangler on Thu Mar 21 2024 12:25:03 GMT+0100 (Central European Standard Time)
// by running `wrangler types`

interface Env {
	DATOCMS_READONLY_API_TOKEN: string;
	INCLUDE_DATOCMS_DRAFTS: string;
	CACHE_INVALIDATION_WEBHOOK_TOKEN: string;
	FASTLY_KEY: string;
	FASTLY_SERVICE_ID: string;
}
