// Generated by Wrangler on Thu Mar 14 2024 16:58:16 GMT+0100 (Central European Standard Time)
// by running `wrangler types`

interface Env {
	DATOCMS_READONLY_API_TOKEN: string;
	INCLUDE_DATOCMS_DRAFTS: string;
}
